name: codestats_flutter
description: View codestats in your phone

publish_to: 'none'

version: 2.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  date_format: ^2.0.6
  provider: ^6.0.2
  rxdart: ^0.27.3
  json_annotation: ^4.4.0
  phoenix_wings: ^1.0.2
  charts_flutter: ^0.12.0
  random_color: ^1.0.6-nullsafety
  dio: ^4.0.6
  path_provider: ^2.0.9
  hydrated: ^2.1.0
  bubble_tab_indicator: ^0.1.6
  flutter_spinkit: ^5.1.0
  flutter_inappwebview: ^5.3.2
  draggable_scrollbar: ^0.1.0
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  share: ^2.0.4
  circular_chart_flutter: ^0.0.2
  fl_chart: ^0.50.1
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.1.5
  build_runner: ^2.1.8

flutter:
  uses-material-design: true

  assets:
    - assets/icon/ic_launcher.png
